import { Punch_in_out } from "../styles";

const RouteName = {
    SPLASH_SCREEN: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGINFIRSTSCREEN: 'LoginFirstScreen',
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    Home_tab:"HomeTab",
    TAB_NAVIGATOR: "TabNavigators",
    FORGOT_PASSWORD: 'ForgotPassword',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICTION_SCREEN: 'NotificationScreen',
    PRIVACY_POLICY_SCREEN: 'PrivacyPolicyScreen',
    LEADTAB: 'LeadTab',
    LANGUAGESCREEN: 'LanguageScreen',
    CREATETASK: 'CreateTaskScreen',
    DEALSTAB: 'DealsTab',
    CONTACTSTAB: 'ContactsTab',
    TASKADD: 'TaskAddScreen',
    ACCOUNTSSCREEN: 'AccountsScreen',
    TASKSSCREEN: 'TasksScreen',
    DAYSUMMARY: 'DaysummaryScreen',
    TEAMSCREEN: 'TeamScreen',
    TEAMLEAVESCREEN: 'TeamLeaveScreen',
    SERVICESTAB: 'ServicesTab',
    ATTENDANCEPROFILE: 'AttendanceProfile',
    PUNCHINOUT: 'AttendancePunchInOut',
    LEAVEAPPLY: 'Leaveapply',
    EODSCREEN:   'EodScreen',
    EXPENSE: 'ExpenseScreen',
    OUTLET: 'OutletScreen',
    OUTLETDETAIL: 'OutletDetailScreen',
    ORDER: 'OrderScreen',
    // ACTIVITY: 'ActivityScreen',
    RETAILACTIVITY: 'RetailActivityScreen',
    MSDACTIVITY: 'MsdActivityScreen',
    CONTACTLIST: 'ContactListScreen',
    EXPENSEHQ: 'ExpenseHqScreen',
    PROFILETAB: 'ProfileTab',
    EDITPROFILE: 'EditProfile',
    ATTENDANCETAB: 'AttendanceTab',
    SKUORDERHISTORY: 'SkuOrderHistoryScreen',
    ATTENDANCEHISTORY: 'AttendanceHistoryScreen',
    RESETPASSWORD: 'ResetPassword',
    ACTIVITYHISTORY: 'ActivityHistoryScreen',
    SKUORDER: 'SkuOrderScreen',
    ORDERHISTORY: 'OrderHistoryScreen',
    REGULIZATION:  'RegulizationScreen',
    REGISTRATIONSUCCESSFUL: 'RegistrationSuccessful',
    APPROVALSCREEN: 'ApprovalScreen',
    SALESANALYSIS:  'SalesAnalysisScreen',
    HOLIDAYSSCREEN: 'HolidaysScreen',
    PAYSTUBDETAILSSCREEN:'PaystubDetailsScreen',
    LEAVEREQUESTSSCREEN:'LeaveRequestsScreen',
    PAYROLLSCREEN:'PayrollScreen',
    CHECKINOUTSCREEN:'CheckInOutScreen'
}
export default RouteName;