export const Colors = {
  theme_background: '#128C7E',
  Light_theme_background: "#128C7E19",
  black_text_color: 'black',
  gray_text_color: '#737272',
  light_gray_text_color: 'lightgray',
  white_text_color: '#ffffff',
  blue_color: 'blue',
  black_color: 'black',
  white_color: 'white',
  amber_color: '#FFC000',
  chinese_silver: '#C8C7C8',
  argent_color: '#C2C0C0',
  ghost_white_color: '#f8f9fc',
  spanish_pink_color: '#F5B9BD',
  spanish_pink_color: '#F5B9BD',
  sandy_tan_color: '#f8d2ba',
  sandy_tan_color: '#fadcc8',
  peach_orange: '#f4aa76',
  diamond_color: '#c1e3f4',
  pale_lavender: '#DCC7F8',
  pale_lavender: '#DCC7F8',
  blue_jeans_color: '#52b2fd',
  light_yellow: "#fef7d6",
  wageningen_green: "#299D35",
  gold_color: "gold",
  red: "red",
  light_green: '#40d375',
  green_color:'green',
  light_normal_gray: 'rgba(0,0,0,0.5)',
  Settings_Colors_1:'#3b60f3',
  Settings_Colors_2:'#ef3bf3',
  Settings_Colors_3:'#fd9627',
  Settings_Colors_4:'#f33b3b',
  Settings_Colors_5:'#ff85eb',
  Settings_Colors_6:'#76f33b',
  Settings_Colors_7:'#f3ec3b',
};
export default Colors;
